context:
  name: httptap
  version: 0.0.8

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/monasticacademy/${{ name }}/archive/v${{ version }}.tar.gz
  sha256: 14d221aefd484b7fb2163765f1281f09699f2ffa0ae4a785effa5cb9c2c6532f

build:
  number: 0
  skip:
    - win
    - osx

requirements:
  build:
    - ${{ compiler("go-cgo") }}
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - go-licenses

tests:
  - script:
      - httptap --help

about:
  homepage: https://github.com/monasticacademy/httptap
  summary: View HTTP/HTTPS requests made by any Linux program
  license: MIT
  license_file:
    - LICENSE
    - library_licenses

extra:
  recipe-maintainers:
    - moritzwilksch
